### ISSUE TITLE
timeout: throw timeout error when the request takes too long

### ISSUE THREAD

**Issue by eamonnmag** [HEPData/hepdata-converter-ws-client#1]
This should stop gunicorn from locking up waiting an unknown amount of time for a request to come back.

**Comment by GraemeWatt** [comment]
@alisonrclarke, do you think you could address this issue before the next release?

**Comment by alisonrclarke** [comment]
Will do. Do you know what's the maximum time a conversion might reasonably take, so we can choose a sensible timeout?

**Comment by GraemeWatt** [comment]
Hmm, not sure, maybe a minute or more for a very large conversion.  Maybe better to avoid hard-coding a value in this package and pass an optional argument `timeout=None` into the `convert` function from the main web app, which is passed on to `requests.get`.  Then the value of `timeout` can be changed more easily without releasing another version of this package.  Probably the `status_code` returned by `requests.get` should also be checked for a `200` value.
