### ISSUE TITLE
Correct call to tarfile.open in 'convert' function

### ISSUE THREAD

**Issue by GraemeWatt** [HEPData/hepdata-converter-ws-client#14]
One of the most frequent causes of failed submission jobs (see HEPData/hepdata#248, addressed by HEPData/hepdata#316), is a `FileNotFoundError` when converting from the `oldhepdata` format (see an example event in [Flower](https://flower.hepdata.net/task/248f8b53-cc06-41e5-9c8b-7314daadba6d) and [Sentry](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/7605/?query=is%3Aunresolved)).  The same exception is sometimes also raised by the `convert_and_store` task (see another example event in [Flower](https://flower.hepdata.net/task/af395159-9339-4f5a-b037-c71f98ce7c13) and [Sentry](https://hepdata-sentry.web.cern.ch/sentry/hepdata-prod/issues/7619/?query=is%3Aunresolved)).  In both cases the exception is raised by this line:
https://github.com/HEPData/hepdata-converter-ws-client/blob/144e8d477689368b78f0cf444c459dcdc00cd9f1/hepdata_converter_ws_client/__init__.py#L96
This looks like invalid syntax.  The first argument should be a keyword argument `mode='r:gz'`, otherwise it is interpreted as being a pathname `name`, explaining the `FileNotFoundError` since a file named `r:gz` does not exist.   What I don't understand is why this works for some calls but not for others.  It might be the case that `name` is normally ignored if a `fileobj` argument is given, but if `fileobj` cannot be opened, then the code attempts to open a pathname `name` instead.  Another case of a missing `mode` appears a few lines below:
https://github.com/HEPData/hepdata-converter-ws-client/blob/144e8d477689368b78f0cf444c459dcdc00cd9f1/hepdata_converter_ws_client/__init__.py#L106
The solution is probably just to replace `'r:gz'` by `mode='r:gz'` in these two lines, but it would be good to have a better understanding of the failure.

**Comment by alisonrclarke** [comment]
Stepping through the code and checking the name, it seems that the name of the tar file is indeed 'r:gz' (in the same directory as the `__init__.py` file) but as we're passing `fileobj` it isn't using the name. 

The [docs](https://docs.python.org/3.6/library/tarfile.html) say:

> If fileobj is specified, it is used as an alternative to a file object opened in binary mode for name. It is supposed to be at position 0.

and:

> If fileobj is given, it is used for reading or writing data. If it can be determined, mode is overridden by fileobj’s mode. fileobj will be used from position 0.

So basically the name isn't being used, and the mode should be able to be determined by the` fileobj`'s mode, which works most of the time.

In the case of the Sentry error you posted it looks like that mode is being incorrectly determined: `xzopen` is for an lzma compressed tar but in a successful test case it goes through `gzopen` which is what we want. I'm not entirely sure why using the wrong mode results in a `FileNotFound` exception but hopefully fixing the mode as you suggested will solve the issue.

**Comment by GraemeWatt** [comment]
Looking at the `tarfile.py` source code, if a `mode` is not specified explicitly, the `open` method iterates through [`gzopen`, `bz2open`, `xzopen`, `taropen`].  If a `ReadError` is encountered from trying to open a file with the wrong method, the next method is tried, returning a `tarfile.Tarfile` object on success.  So this works most of the time (the bug has been present since 2015), since `gzopen` is tried first, but if `gzopen` fails for some reason, the code proceeds to `bz2open`, then `xzopen`.  The exception then comes executing `self.name = os.path.abspath(name)` where `name = 'r:gz'`, which calls `cwd = os.getcwd()` giving the `FileNotFoundError` exception.  I don't understand why this exception is raised.  Calling `os.path.abspath('r:gz')` should be valid even if a file called `r:gz` does not exist, so it seems that `os.getcwd()` is not defined.  In any case, specifying `mode='r:gz'` should ensure that only `gzopen` is called, not the other methods like `xzopen`.  A `ReadError` should be returned if the file cannot be opened, which we already propagate.
